name: 'ai18n upload strings'
description: 'upload a translation.yml file to ai18n'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  strings_path:
    description: 'Path to the ai18n-strings.yml file'
    required: true
  target_locales:
    description: 'An array of locales that you want to generate translations for'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
